theme = "themes/nightfox.json"

[keys.insert]
Enter = "NewLine"
Backspace = "DeletePreviousChar"
Esc = { EnterMode = "Normal" }

[keys.normal]
"o" = [ "InsertLineBelowCursor", { EnterMode = "Insert" } ]
"O" = [ "InsertLineAtCursor", { EnterMode = "Insert" } ]
"q" = "Quit"
"G" = "MoveToBottom"
"g" = { "g" = "MoveToTop" }
"u" = "Undo"
"p" = [ "MoveUp", "MoveRight" ]
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"Up" = "MoveUp"
"k" = "MoveUp"
"j" = "MoveDown"
"h" = "MoveLeft"
"l" = "MoveRight"
"0" = "MoveToLineStart"
"Home" = "MoveToLineStart"
"$" = "MoveToLineEnd"
"End" = "MoveToLineEnd"
"Ctrl-b" = "PageUp"
"Ctrl-f" = "PageDown"
"x" = "DeleteCharAtCursorPos"
"d" = { "d" = "DeleteCurrentLine", "b" = "DumpBuffer" }
"z" = { "z" = "MoveLineToViewportCenter" }
"i" = { EnterMode = "Insert" }

