# Audit configuration for cargo-audit

[advisories]
# The idna vulnerability is in a transitive dependency through deno_ast
# which we cannot update without breaking changes. The vulnerability is
# related to Punycode label validation which doesn't affect our use case.
ignore = ["RUSTSEC-2024-0421"]

[yanked]
# Disable yanked crate warnings
enabled = false